### ISSUE TITLE
Clarification needed on the Snowball's Usable capacity in the FAQ

### ISSUE THREAD

**Issue by jsbonso** [awsdocs/aws-snowball-developer-guide#3]
Hi Team,

Just want to confirm about the usable capacity of Snowball. Is the usable capacity the **total data that you can actually store** on the snowball device?

It seems to be contradicting itself when we factor in the usable capacity on the example in the above FAQ which says that you can move/store 150 TB of data with two 80 TB of Snowball devices. Considering that you only have 72 TB of usable capacity out of the 80 TB device ( 72 x 2 = 144 ), then this calculation seems to be wrong.

Please see the below screenshot for reference:
https://aws.amazon.com/snowball/faqs/#When_to_use_Snowball

![image](https://user-images.githubusercontent.com/4216253/50145618-1d6ed280-0306-11e9-81a9-ef31159dc4b9.png)

Thank you in advance for your support on this matter.

Cheers,
Jon Bonso

**Comment by jsbonso** [comment]
Any update on this, guys? It's been a year :(

**Comment by davidmgre** [comment]
Hi @jsbonso, 

Thanks for reaching out and I'm sorry for the delay in response here. 

The [documentation page](https://docs.aws.amazon.com/snowball/latest/developer-guide/device-differences.html) has a list of the usable capacity of Snowball devices. 

Each device has different storage capacities, as follows:

* Snowball
	* 50 TB (42 TB usable) only available in US regions
	* 80 TB (72 TB usable)
* Snowball Edge Storage Optimized
	* 100 TB (80 TB usable)
* Snowball Edge Compute Optimized
	* 42 TB (39.5 usable) plus 7.68 TB of dedicated NVMe SSD for compute instances
* Snowball Edge Compute Optimized with GPU
	* 42 TB (39.5 usable) plus 7.68 TB of dedicated NVMe SSD for compute instances

Additionally, the [FAQ page](https://aws.amazon.com/snowball/faqs/#When_to_use_Snowball) you referenced has been updated since your original outreach. 

Please let us know if this addresses your question.

**Comment by jsbonso** [comment]
Thanks  @davidmichaelgreen! Finally, someone replied after **1 year and 6 months** haha but yeah, I still appreciate the response. 

It would also be great if you can remove the AWS Snowball docs since this service has already been deprecated,  and transitioned to Snowball Edge.
 
It seems that the information you shared for 50 TB and 80 TB for the **Standard** AWS Snowball device shouldn't matter anymore because only the Snowball **_Edge_** type only exists.

Anyway, it's good to see that the FAQ was finally updated since its calculation (for usability capacity) is totally off, as per my statement. 

Thanks and have a great weekend!

Cheers,
Jon Bonso @ Tutorials Dojo

**Comment by davidmgre** [comment]
Thanks for the feedback, @jsbonso. We will review and modify as needed. Please keep the feedback coming. Tag me on anything AWS-related and I'll make sure to get a response from the teams.

**Comment by jsbonso** [comment]
Much appreciated @davidmichaelgreen! I actually have 2 pending pull-requests that you could help :) I'll tag you bro.

Cheers,
Jon Bonso @ Tutorials Dojo
